Maya2022 Update
qualisys/QTM-Connect-For-Maya pull request #3
Opened 2021-08-30 14:49 UTC by Thingvold

Maya changed to Python 3 in version 2022.  Most  changes are related to code upgrades (print statements and some FileIO methods)

Some additional changes:

Upgraded to QAvatar with upper arm roll bones and extra clavicle.  Sample data updated for this.

Removed special case Y up local rotations for backward compatibility with the original QAvatar.

2021-12-01 15:32 UTC, EmilRosenquist commented
Make it clear that we need to use versions before this one to build the plugin for older versions of Maya since they don't support Python 3.

2021-12-10 10:11 UTC, EmilRosenquist approved these changes
Python 3 changes looks good, I'm not sure if all cases are covered when importing these different attributes on segments (Couplings, goals etc..). Can you ensure that those are correct @Henrik-Norgren

2021-12-10 10:37 UTC, Wyst3r commented
@EmilRosenquist Attributes seems fine I think (I guess we don't care about backwards compatibility here?), only thing is that coupling DOF is assumed to be the same as the DOF being coupled (In QTM, RotationZ could in theory be coupled to e.g. RotationX). Is that intentional @Thingvold?

2021-12-10 13:53 UTC, Thingvold commented
Making the assumption that the DOFs are the same axis avoids adding a lot of complexity to the attributes.  It's pretty rare to need it so I opted out of implementing it.

2021-12-13 09:16 UTC, Henrik-Norgren requested changes

2021-12-13 09:16 UTC, Henrik-Norgren commented on QExportSolver.py
> +                self._Write( Spaces(level+3)+"<Constraints LowerBound=\""+str(lb)+"\" UpperBound=\""+str(ub)+"\"/>")
Constraints -> Constraint

2021-12-13 09:16 UTC, Henrik-Norgren commented on QExportSolver.py
> +                #self._Write( Spaces(level+2)+"<RotationY LowerBound=\""+str(lb)+"\" UpperBound=\""+str(ub)+"\"/>")
Any reason to keep the commented code?

2021-12-13 12:09 UTC, Thingvold commented on QExportSolver.py
> +                #self._Write( Spaces(level+2)+"<RotationY LowerBound=\""+str(lb)+"\" UpperBound=\""+str(ub)+"\"/>")
No.

2021-12-16 22:27 UTC, Thingvold commented on QExportSolver.py
> +                self._Write( Spaces(level+3)+"<Constraints LowerBound=\""+str(lb)+"\" UpperBound=\""+str(ub)+"\"/>")
Should be good now.

2021-12-17 05:52 UTC, Henrik-Norgren approved these changes

2021-12-20 14:09 UTC, merged